### ISSUE TITLE
Grading Overview

### ISSUE THREAD

**Issue by Lucav17** [tedcfc/The_Tea_Cozy#1]
### Criteria 1: HTML and CSS Linking  
* _Score Level:_ 4
* _Comment(s):_ Well done importing your CSS via a link tag in your HTML! For future cases when you build larger projects, make sure to keep your CSS and HTML in separate folders!
 
### Criteria 2: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ Well done implementing the spec! This shows a strong understanding of web development and HTML and CSS!
 
### Criteria 3: HTML Elements and Content
* _Score Level:_ 4
* _Comment(s):_ Your HTML was commented, well indented, and easy to read. The code blocks all looked correct too!
 
### Criteria 4: CSS Selectors and Syntax
* _Score Level:_ 4
* _Comment(s):_ Good job with your CSS selectors. Styling wise just make sure to have a space prepend the opening bracket of each selector, otherwise well done!
 
### Overall Score: 16/16
Great job! I think next step is to start learning Javascript and how to manipulate the DOM!

**Comment by tedcfc** [comment]
Beautiful!
Thank you Lucav17!!
I will follow your advice on future projects and have been playing with some js and jquery, but not much.
It is an area I would like to study, learn and apply.
All the best,
Ted
